export const seedImage = [
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,w_400/v1713749566/lele_n0mwa0.jpg',
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,w_400/v1713750566/mas_tkuvxv.jpg',
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,w_400/v1713749745/patin_pfn49h.jpg',
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,w_400/v1713749500/nila_brklod.jpg',
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,h_250,w_400/v1713749746/gurame_e80j3l.jpg'
];

export const seedFishCategories: string[] = [
    'lele',
    'patin',
    'gurami',
    'nila',
    'mas',
    'bawal'
];

export const seedNameFish: { [key: string]: string } = {
    'lele': 'Ikan Lele',
    'patin': 'Ikan Patin',
    'gurami': 'Ikan Gurami',
    'nila': 'Ikan Nila',
    'mas': 'Ikan Mas',
    'bawal': 'Ikan Bawal'
};

export const seedFishTitles: string[] = [
    'Ikan Segar dari Tambak',
    'Ikan Budidaya Terbaik',
    'Ikan Segar Peternakan',
    'Ikan Berkualitas Tinggi',
    'Ikan Segar Peternakan',
    'Ikan Segar Harga Terbaik'
];

export const seeddescriptionFish: string[] = [
    'ikan air tawar yang mudah dibudidayakan. Dagingnya sangat cocok untuk diolah menjadi sate atau pepes.',
    'ikan air tawar yang memiliki daging putih dan lembut. Ikan ini sering dijadikan bahan utama dalam masakan tradisional.',
    'ikan air tawar yang memiliki tekstur daging yang kenyal. Ikan ini sering diolah menjadi berbagai masakan lezat.',
    'ikan air tawar yang populer di Indonesia. Ikan ini memiliki daging yang lezat dan cocok untuk dikonsumsi.',
    'ikan air tawar yang memiliki rasa yang lezat. Dagingnya cocok untuk digoreng atau dibakar.',
    'ikan air tawar yang memiliki daging yang tebal dan lezat. Ikan ini sering diolah menjadi pesmol atau pepes.'
];

export const seedFishDescription: string[] = [
    'ikan hasil langsung dari tambak. Dijamin segar dan berkualitas.',
    'ikan hasil budidaya terbaik. Siap untuk dikonsumsi.',
    'ikan hasil dari peternakan ikan. Cocok untuk berbagai jenis masakan.',
    'ikan hasil kualitas terbaik. Dapatkan sekarang juga.',
    'ikan hasil langsung dari peternakan. Lezat dan bergizi.',
    'ikan hasil langsung dari perairan air tawar. Cocok untuk hidangan istimewa.'
];

export const seedTags: string[] = [
    'benih',
    'konsumsi'
];

export const seedName: string[] = [
    'Budi Santoso',
    'Agus Riyadi',
    'Siti Rahayu',
    'Dewi Lestari',
    'Rina Anggraini',
    'Rudi Hartono',
    'Lina Widayanti',
    'Joko Susanto',
    'Wati Purwanti',
    'Eka Suryadi',
    'Sinta Permata',
    'Yudi Pranata',
    'Dina Safitri',
    'Bayu Wibowo',
    'Tari Puspita',
    'Rian Saputra',
    'Dian Kusuma',
    'Ani Setiawan',
    'Rina Septiani',
    'Adi Nugroho',
    'Putri Hapsari',
    'Iwan Setiawan',
    'Dwi Cahyono',
    'Yani Kusuma',
    'Mira Susanti',
    'Rika Sari',
    'Reni Wulandari',
    'Tono Santoso',
    'Rita Permata',
    'Nia Fitriani',
    'Hani Astuti',
    'Doni Prasetyo',
    'Rahma Anggraini',
    'Aditya Nugraha',
    'Rima Damayanti',
    'Indra Cahya',
    'Astuti Purnama',
    'Firman Setiawan',
    'Rizki Ramadhan',
    'Sari Wulandari',
    'Fajar Pratama',
    'Nur Hidayah',
    'Risky Pratama',
    'Taufik Hidayat',
    'Rani Permata',
    'Jeni Kurniawati',
    'Rina Novianti',
    'Aditya Kusuma',
];

export const seedTambak: string[] = [
    'Tambak Aji',
    'Tambak Lorok',
    'Tambak Rejo',
    'Tambak Sari',
    'Tambak Bayan',
    'Tambak Wedi',
    'Tambak Cemara',
    'Tambak Kenanga',
    'Tambak Jaya',
    'Tambak Asri',
    'Tambak Makmur',
    'Tambak Mulia',
    'Tambak Mulya',
    'Tambak Indah',
    'Tambak Damai',
    'Tambak Bahagia',
    'Tambak Lestari',
    'Tambak Sentosa',
    'Tambak Harapan',
    'Tambak Manunggal',
    'Tambak Mekar',
    'Tambak sejahtera',
];

export const seedPlat = [
    'B3O23KEZ',
    'B3A4R5U2',
    'B8C2X4V5',
    'B1M3U8R7',
    'B5M2W3C9',
    'B7Y4V3K9',
    'B1F9X7Z4',
    'B3E8H1T6',
    'B2N7Y9U6',
    'B4B7X8D5',
    'B1N3P8V7',
    'B8G2S5U6',
    'B2G6K4X8',
    'B4F7J1X3',
    'B6P2Z4U1',
    'B5F2J9X6',
    'B8N1X3P2',
    'B9C4X5V1',
    'B3S8Z2U4',
    'B5E2H8V1',
    'B7D1R5P3',
    'B1K7C2T5',
    'B4W3T9S1',
    'B1S5R2M9',
    'B6R4U1P8',
    'B9T7H5K1',
    'B1D8W7M5',
    'B2P7U5S1',
    'B5Z2U1N4',
    'B3K5H8Z7',
    'B6S2V4T1',
    'B8K1X4W7',
    'B2J5P8C4',
    'B9F1M4W6',
    'B3P9Z1C5',
    'B2B4F7X3',
    'B5Z3X6J4',
    'B1U5D3R7',
    'B7J8Z5T2',
    'B9X2W7V5',
    'B4K7N1S8',
    'B9X4P1N6',
    'B2V4C8P3',
    'B8Z1N4K2',
    'B6F3C8S1',
    'B8H3U9P2',
    'B7U1R8Z2',
    'B3X5W9V7',
    'B4J2S7N1',
    'B5H1W3Z9',
    'B8P5F3T1',
    'B6U2H9R3',
    'B4Z2K7D1',
    'B6D1M7Z3',
    'B3T2P7M1',
    'B1R8N3X2',
    'B5K1P9C4',
    'B7X4D3F1',
    'B2Z8F3X7',
    'B9R2S5T7',
    'B7V2H9D5',
    'B6J1W4T9',
    'B3C5V7S1',
    'B2K7H4X6',
    'B8Z1M3P9',
    'B4V5P2R8',
    'B9X2N5S1',
    'B1H9V5R8',
    'B3P5U9K7',
    'B7W9N3T2',
    'B2X4V9R1',
    'B5Z1M7C2',
    'B6F3P1R8',
    'B7K9J4X1',
    'B8P2D3X9',
    'B2R7W9J4',
    'B9H8X4W1',
    'B7K2N4U1',
    'B5S7U8T2',
    'B4B7X2J6',
    'B8F3Z9W7',
    'B6R1T7N5',
    'B9Z3K7X1',
    'B3F7T9S2',
    'B1N3U8M5',
    'B9H1P4R6',
    'B6D1J7X9',
    'B5P9V2N3',
    'B8M3Z2C1',
    'B2X4V5T8',
    'B4F7H1M3',
    'B9R7T4P1',
    'B1S8U5R4',
    'B4K7N9W3',
    'B2Z8R5V7',
    'B3P7W9T1',
    'B9U2X5Z3',
    'B6J8H3R1',
    'B5F3V2M8',
    'B6X2R9C1'
];
