export const seedImage = [
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,w_400/v1713749566/lele_n0mwa0.jpg',
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,w_400/v1713750566/mas_tkuvxv.jpg',
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,w_400/v1713749745/patin_pfn49h.jpg',
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,w_400/v1713749500/nila_brklod.jpg',
    'https://res.cloudinary.com/diaej365u/image/upload/c_scale,h_250,w_400/v1713749746/gurame_e80j3l.jpg'
];

export const seedFishCategories: string[] = [
    'lele',
    'patin',
    'gurami',
    'nila',
    'mas',
    'bawal'
];

export const seedTags: string[] = [
    'benih',
    'konsumsi'
];

export const seedName: string[] = [
    'Budi Santoso',
    'Agus Riyadi',
    'Siti Rahayu',
    'Dewi Lestari',
    'Rina Anggraini',
    'Rudi Hartono',
    'Lina Widayanti',
    'Joko Susanto',
    'Wati Purwanti',
    'Eka Suryadi',
    'Sinta Permata',
    'Yudi Pranata',
    'Dina Safitri',
    'Bayu Wibowo',
    'Tari Puspita',
    'Rian Saputra',
    'Dian Kusuma',
    'Ani Setiawan',
    'Rina Septiani',
    'Adi Nugroho',
    'Putri Hapsari',
    'Iwan Setiawan',
    'Dwi Cahyono',
    'Yani Kusuma',
    'Mira Susanti',
    'Rika Sari',
    'Reni Wulandari',
    'Tono Santoso',
    'Rita Permata',
    'Nia Fitriani',
    'Hani Astuti',
    'Doni Prasetyo',
    'Rahma Anggraini',
    'Aditya Nugraha',
    'Rima Damayanti',
    'Indra Cahya',
    'Astuti Purnama',
    'Firman Setiawan',
    'Rizki Ramadhan',
    'Sari Wulandari',
    'Fajar Pratama',
    'Nur Hidayah',
    'Risky Pratama',
    'Taufik Hidayat',
    'Rani Permata',
    'Jeni Kurniawati',
    'Rina Novianti',
    'Aditya Kusuma',
];

export const seedTambak: string[] = [
    'Tambak Aji',
    'Tambak Lorok',
    'Tambak Rejo',
    'Tambak Sari',
    'Tambak Bayan',
    'Tambak Wedi',
    'Tambak Cemara',
    'Tambak Kenanga',
    'Tambak Jaya',
    'Tambak Asri',
    'Tambak Makmur',
    'Tambak Mulia',
    'Tambak Mulya',
    'Tambak Indah',
    'Tambak Damai',
    'Tambak Bahagia',
    'Tambak sejahtera',
    'Tambak Lestari',
    'Tambak Sentosa',
    'Tambak Harapan',
    'Tambak Manunggal',
    'Tambak Mekar',
    'Tambak sejahtera',
    'Tambak sejahtera',
    'Tambak sejahtera',
];
